name: News Pipeline CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install flake8
          # يمكنك إضافة pytest هنا مستقبلاً

      - name: Lint with flake8
        run: |
          # التوقف إذا كان هناك أخطاء برمجية قاتلة
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Build Recommender Image
        run: |
          # نستخدم -f لأن الـ Dockerfile في الـ Root
          # والنقطة (.) تعني أننا نستخدم المجلد الحالي كـ Context
          docker build -t news-recommender:latest -f Dockerfile .